[package]
name = "tank_game_bevy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6.0"
heron = { version = "1.1.0", features = ["3d"] }
